// Generated by gencpp from file packageprova/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PACKAGEPROVA_MESSAGE_ADDTWOINTS_H
#define PACKAGEPROVA_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <packageprova/AddTwoIntsRequest.h>
#include <packageprova/AddTwoIntsResponse.h>


namespace packageprova
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace packageprova


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::packageprova::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::packageprova::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::packageprova::AddTwoInts > {
  static const char* value()
  {
    return "packageprova/AddTwoInts";
  }

  static const char* value(const ::packageprova::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::packageprova::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::packageprova::AddTwoInts >
template<>
struct MD5Sum< ::packageprova::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::packageprova::AddTwoInts >::value();
  }
  static const char* value(const ::packageprova::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::packageprova::AddTwoIntsRequest> should match
// service_traits::DataType< ::packageprova::AddTwoInts >
template<>
struct DataType< ::packageprova::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::packageprova::AddTwoInts >::value();
  }
  static const char* value(const ::packageprova::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::packageprova::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::packageprova::AddTwoInts >
template<>
struct MD5Sum< ::packageprova::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::packageprova::AddTwoInts >::value();
  }
  static const char* value(const ::packageprova::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::packageprova::AddTwoIntsResponse> should match
// service_traits::DataType< ::packageprova::AddTwoInts >
template<>
struct DataType< ::packageprova::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::packageprova::AddTwoInts >::value();
  }
  static const char* value(const ::packageprova::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACKAGEPROVA_MESSAGE_ADDTWOINTS_H
